spring:
  datasource:
    url: jdbc:mysql://activity-db:3306/activityservice
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9050


