spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activitytracker 
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9050


