server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: User-Service-Public
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/users/auth/**
          filters:
            - StripPrefix=2

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/users/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: Project-Service
          uri: lb://Project-Service
          predicates:
            - Path=/api/v1/projects/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: Task-Service
          uri: lb://Task-Service
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: Activity-Service
          uri: lb://Activity-Tracker
          predicates:
            - Path=/api/v1/activity/**
          filters:
            - StripPrefix=3
            - AuthenticationFilter

        - id: Notification-Service
          uri: lb://Notification-Service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

jwt:
  secretKey: ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay


