spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamprashantverma/PMS-Config-Server
          username: iamprashantverma
          password: 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
          default-label: main
  profiles:
    active: dev
      
server:
  port: 8888

eureka:
  client:
    enabled: false




