name: "Prashant"
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.yourpackage.*"  # Specify your package instead of "*"
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/projectservice
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true

  # Server Config
  server:
    servlet:
      context-path: /project
    port: 9020
