spring:
  datasource:
    url: jdbc:mysql://task-db:3306/taskservice?user=root
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    websocket:
      path: /graphql
      enabled: true
server:
  port: 9030
  servlet:
    context-path: /tasks
